// examples/reactive-preact/src/App.tsx
import { useEffect, useState } from "preact/hooks";
import grab from "grab-url";

type UserState = Partial<{
  name: string;
  email: string;
  isLoading: boolean;
  error: string;
}>;

export default function App() {
  const [userState, setUserState] = useState<UserState>({});

  useEffect(() => {
    // Same shape as the React example — preact/hooks' setter takes the
    // loading/error/data states grab hands it.
    grab("https://jsonplaceholder.typicode.com/users/1", {
      response: setUserState,
    });
  }, []);

  return (
    <main style={{ fontFamily: "system-ui, sans-serif", maxWidth: 480, margin: "3rem auto" }}>
      <h1>User Profile</h1>
      {userState.isLoading && <div>Loading...</div>}
      {userState.error && <div>Error: {userState.error}</div>}
      {userState.name && (
        <div>
          <h2>{userState.name}</h2>
          <p>{userState.email}</p>
        </div>
      )}
    </main>
  );
}

// examples/reactive-solid/src/App.tsx
import { createMutable } from "solid-js/store";
import { onMount, Show } from "solid-js";
import grab from "grab-url";

type UserState = {
  name?: string;
  email?: string;
  isLoading?: boolean;
  error?: string;
};

export default function App() {
  // createMutable is a deep proxy, so the writes grab makes to this object are
  // the reactive updates — no setter, no signal to thread through.
  const user = createMutable<UserState>({});

  onMount(() => {
    grab("https://jsonplaceholder.typicode.com/users/1", { response: user });
  });

  return (
    <main style={{ "font-family": "system-ui, sans-serif", "max-width": "480px", margin: "3rem auto" }}>
      <h1>User Profile</h1>
      <Show when={user.isLoading}>
        <div>Loading...</div>
      </Show>
      <Show when={user.error}>
        <div>Error: {user.error}</div>
      </Show>
      <Show when={user.name}>
        <div>
          <h2>{user.name}</h2>
          <p>{user.email}</p>
        </div>
      </Show>
    </main>
  );
}
